#!/usr/bin/env bash
# Vendor the canonical tables and crate version into this package before
# packing. The repository keeps no duplicates: `tables/salutation.json`,
# `tables/farewell/` and `Cargo.toml` at the cnice root stay canonical;
# `src/generated/` and `typst/generated/` are regenerated.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

mkdir -p "$HERE/src/generated" "$ROOT/typst/generated"

VERSION="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed 's/.*"\(.*\)"/\1/')"

python3 - "$HERE" "$ROOT" "$VERSION" <<'EOF'
import json
import sys

here, root, version = sys.argv[1], sys.argv[2], sys.argv[3]
with open(f"{root}/tables/salutation.json", encoding="utf-8") as handle:
    salutation = json.load(handle)
with open(f"{root}/tables/farewell/closing.json", encoding="utf-8") as handle:
    closing = json.load(handle)
greet_out = (
    "// GENERATED by scripts/sync-assets.sh — do not edit.\n"
    "export interface SalutationHonorific {\n"
    "  group: string;\n"
    "  display: string;\n"
    "}\n"
    "export interface SalutationEntry {\n"
    "  honorifics: Record<string, SalutationHonorific>;\n"
    "  titles: Record<string, string>;\n"
    "  sole_titles: string[];\n"
    "  filler: string[];\n"
    "  named: Record<string, string>;\n"
    "  formal: string;\n"
    "  comma: boolean;\n"
    "  source_norms: string;\n"
    "  review?: string;\n"
    "}\n"
    "export interface SalutationFile {\n"
    "  locales: Record<string, SalutationEntry>;\n"
    "  fallback: string;\n"
    "}\n"
    f"export const PACKAGE_VERSION: string = {json.dumps(version)};\n"
    f"export const SALUTATION_TABLE: SalutationFile = {json.dumps(salutation, ensure_ascii=False)};\n"
)
with open(f"{here}/src/generated/greet-tables.ts", "w", encoding="utf-8") as handle:
    handle.write(greet_out)
farewell_out = (
    "// GENERATED by scripts/sync-assets.sh — do not edit.\n"
    f"export const PACKAGE_VERSION: string = {json.dumps(version)};\n"
    f"export const CLOSING_TABLE: unknown = {json.dumps(closing, ensure_ascii=False)};\n"
)
with open(f"{here}/src/generated/farewell-tables.ts", "w", encoding="utf-8") as handle:
    handle.write(farewell_out)


def typst_str(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


entries = ",\n  ".join(
    f"{typst_str(key)}: {typst_str(val)}" for key, val in closing["locales"].items()
)
typ = (
    "// GENERATED by js/@corbet-foss/cnice/scripts/sync-assets.sh — do not edit.\n"
    "#let closing-table = (\n"
    f"  locales: (\n  {entries},\n  ),\n"
    f"  fallback: {typst_str(closing['fallback'])},\n"
    ")\n"
)
with open(f"{root}/typst/generated/closing.typ", "w", encoding="utf-8") as handle:
    handle.write(typ)
print(f"synced tables/salutation.json, tables/farewell/closing.json, version {version}")
EOF

python3 "$ROOT/scripts/sync-python.py"
